---
title: "the hpk times"
author: "Andrew Martin"
date: "July 14, 2015"
output: html_document
---

```{r helpers, message=FALSE, error=FALSE, warning=FALSE, include=FALSE}
knitr::knit('cur_hpk_prep.Rmd', tangle = TRUE)
source('cur_hpk_prep.R')
library(DT)
```


```{r global_options, include=FALSE}

knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE, fig.device = 'svg', cache = FALSE)

```

## _day `r n_days` of the season_

# Yesterday
to come

# Previous 7 days

```{r week_standings, cache=FALSE}

DT::datatable(
  all_table_stats(hpk_week) %>% as.data.frame(), 
  rownames = FALSE,
  options = list(pageLength = 12, dom = 'tip')
)

DT::datatable(
  all_table_rank(hpk_week) %>% as.data.frame(), 
  rownames = FALSE,
  options = list(pageLength = 12, dom = 'tip')
)

```

# Previous 14 days

```{r prev_2week, cache=FALSE}

DT::datatable(
  all_table_stats(hpk_2week) %>% as.data.frame(), 
  rownames = FALSE,
  options = list(pageLength = 12, dom = 'tip')
)

DT::datatable(
  all_table_rank(hpk_2week) %>% as.data.frame(), 
  rownames = FALSE,
  options = list(pageLength = 12, dom = 'tip')
)

```

# Previous 30 days

```{r month_standings, cache=FALSE}

DT::datatable(
  all_table_stats(hpk_month) %>% as.data.frame(), 
  rownames = FALSE,
  options = list(pageLength = 12, dom = 'tip')
)

DT::datatable(
  all_table_rank(hpk_month) %>% as.data.frame(), 
  rownames = FALSE,
  options = list(pageLength = 12, dom = 'tip')
)

```

# Points Change, previous 7 days

```{r points_change7}

ranks_yest <- all_table_rank(hpk_clean) %>% dplyr::arrange(owner) %>% as.data.frame()
hpk_7days_ago <-  hpk_clean %>% dplyr::filter(
  date < yesterday & date < season_days[n_days-6] 
)
ranks_7days_ago <- all_table_rank(hpk_7days_ago) %>% dplyr::arrange(owner) %>% as.data.frame()
change_7 <- cbind(ranks_yest[, c(1, 15)], ranks_yest[, 2:14] - ranks_7days_ago[, 2:14]) %>% dplyr::arrange(-points)

DT::datatable(
  change_7, 
  options = list(pageLength = 12, dom = 'tip')
)

```

# Points Change, previous 30 days

```{r points_change30}

ranks_yest <- all_table_rank(hpk_clean) %>% dplyr::arrange(owner) %>% as.data.frame()
hpk_30days_ago <-  hpk_clean %>% dplyr::filter(
  date < yesterday & date < season_days[n_days-29] 
)
ranks_30days_ago <- all_table_rank(hpk_30days_ago) %>% dplyr::arrange(owner) %>% as.data.frame()
change_30 <- cbind(ranks_yest[, c(1, 15)], ranks_yest[, 2:14] - ranks_30days_ago[, 2:14]) %>% dplyr::arrange(-points)

DT::datatable(
  change_30, 
  options = list(pageLength = 12, dom = 'tip')
)

```


# Best hitting (whole season)

```{r hit_only}

DT::datatable(
  best_h(hpk_clean), 
  options = list(pageLength = 12, dom = 'tip')
)

```

# Best pitching (whole season)

```{r pitch_only}

DT::datatable(
  best_p(hpk_clean), 
  options = list(pageLength = 12, dom = 'tip')
)

```

# Average Place

```{r av_place, cache=FALSE}

rank_avg

```

# Days in Place

```{r days, cache=FALSE}

DT::datatable(
  rank_wide, 
  rownames = FALSE,
  options = list(pageLength = 12, dom = 'tip')
)

```

# Projections


### _to come_

