install.packages("rmarkdown")
install.packages("DT")
install.packages("ggplot2")
install.packages("readr")
install.packages("dplyr")
install.packages("zoo")
install.packages("tidyr")
install.packages("magrittr")
install.packages("fitdistrplus")
install.packages("httr")
install.packages("XML")
install.packages("devtools")
install.packages("knitr")
devtools::install_github('cloudyr/aws.signature')
devtools::install_github('cloudyr/aws.s3')
devtools::install_github("almartin82/RMandrill", ref = 'almartin')