---
title: "sim_musings"
author: "Andrew Martin"
date: "July 16, 2015"
output: html_document
---


```{r helpers, message=FALSE, error=FALSE, warning=FALSE, include=FALSE}
knitr::knit('cur_hpk_prep.Rmd', tangle = TRUE)
source('cur_hpk_prep.R')
library(DT)
```


#vs hist dist
ok!  now that we have rolling data, compare to historic dist

for each owner/stat, how do they compare?

per stat, compare to previous distributions

```{r hit_dist}
ggplot(
  data = hpk_hist %>% dplyr::filter(hit_pitch == 'hit'),
  aes(
    x = mean_7
  )
) +
stat_density() +
theme_bw() +
facet_grid(
 facets = stat_name ~ .,
 scales = 'free'
)
```

compare mean_14, mean_21, etc
```{r what_mean}

ggplot(  
  data = hpk_hist %>% dplyr::filter(stat_name == 'RBI')) +
  geom_density(
    aes(x = mean_7)
  ) +
  geom_density(
    aes(x = mean_14)
  ) +  
  geom_density(
    aes(x = mean_21)
  ) +  
  geom_density(
    aes(x = mean_28)
  ) + 
  geom_density(
    aes(x = mean_35)
  ) +   
  theme_bw()

```

ok we're going to roll with mean21

# sim
assume 181 calendar days of baseball

```{r}

sim_season <- function(
  yesterday_df, season_df, mean_lookback = 'mean_21', sd_lookback = 'sd_21'
) {
  #means and sds
  hpk_means <- yesterday_df[, c('stat_id', 'date', 'team_key', 'stat_name', 'hit_pitch', mean_lookback)]
  hpk_sds <- yesterday_df[, c('stat_id', 'date', 'team_key', 'stat_name', 'hit_pitch', sd_lookback)]
  
  #standings
  hpk_standings <- all_table_stats(season_df)

  days_remain <- 181 - n_days
  
  #get the full hist with this many remaining
  hist_comps <- hpk_hist %>%
    dplyr::filter(days_till_end < get('days_remain'))
  
  #get the stat values on *that day* (remaining) so we can watch the random
  #walk of the values.  eg the baseline
  comp_baseline <- hpk_hist %>%
    dplyr::filter(days_till_end == get('days_remain'))
  names(comp_baseline)[names(comp_baseline) == mean_lookback] <- 'mean_baseline'
  names(comp_baseline)[names(comp_baseline) == sd_lookback] <- 'sd_baseline'
  
  hist_comps <- hist_comps %>%
    dplyr::left_join(
      comp_baseline %>% 
        dplyr::select(team_key, stat_name, mean_baseline, sd_baseline),
      by = c('team_key', 'stat_name')
    )
  
  #difference
  hist_comps$mean_delta <- hist_comps$mean_21 - hist_comps$mean_baseline
  hist_comps$sd_delta <- hist_comps$sd_21 - hist_comps$sd_baseline

  n_walks <- 10
  
  #only the scoring stats
  yesterday_iterable <- yesterday_df %>% dplyr::filter(
    stat_name %in% c('R', 'RBI', 'SB', 'TB', 'W', 'SV', 'K')
  )
  
  #iterate over the current stats
  for (i in 1:nrow(yesterday_iterable)) {
    this_row <- yesterday_iterable[i, ]
    this_stat <- hist_comps[hist_comps$stat_name == this_row$stat_name, ]
    
    #sample n times
    unq_teams <- this_stat$team_key %>% unique()
    sampled_teams <- sample(unq_teams, n_walks, replace = TRUE)
    sampled_teams <- data.frame(
      team_key = sampled_teams,
      sim_number = c(1:n_walks),
      stringsAsFactors = FALSE
    )
    
    #get the mean walks for each team
    sim_walks <- sampled_teams %>%
      dplyr::inner_join(this_stat, by = 'team_key') %>%
      tbl_df()
    
    sim_walks$sim_mean_walk <- sim_walks$mean_delta + this_row$mean_21
    sim_walks$sim_sd_walk <- sim_walks$sd_delta + this_row$sd_21
    
    #for each sim, draw from the mean walk
    for (i in 1:n_walks) {
      this_walk <- sim_walks %>% dplyr::filter(sim_number == i)q
    #end n_walks loop
    }
    
  #end iterable stats
  }

#end sim_season function  
}

sim_season(hpk_yest, hpk_clean)
yesterday_df <- hpk_yest
season_df <- hpk_clean
mean_lookback <- 'mean_21'
sd_lookback <- 'sd_21'

#plot it, so we can see
ggplot(
  data = hist_comps,
  aes(
    x = days_till_end,
    y = mean_delta,
    group = team_key,
    color = manager
  )
) + 
geom_line(
  alpha = 0.5
) +
theme_bw() +
facet_grid(
  hit_pitch ~ stat_name
)

```

```{r season_min}

ggplot(
  data = hpk_hist %>% dplyr::filter(stat_name == 'AB'),
  aes(
    x = day_of_season,
    y = mean_21,
    group = team_key,
    color = manager
  )
) +
geom_line(
  alpha = 0.2,
  size = 0.5,
  color = 'gray80'
) +
theme_bw() +
theme(
  panel.grid = element_blank(),
  legend.position = "bottom"
) +
stat_smooth(se = FALSE, size = 1, n = 20) +
scale_color_brewer(palette = "Spectral") +
scale_x_continuous(
  limits = c(50, 190)
) +
scale_y_continuous(
  limits = c(9, 22)
)


```


# errata
verifying omar's runs
```{r}
hpk_clean %>%
  dplyr::filter(team_key == '346.l.49099.t.5' & stat_name == 'SB') %>%
  dplyr::group_by(team_key, stat_name) %>%
  dplyr::mutate(
    cumsum = cumsum(value)
  ) %>%
  dplyr::select(
    date, cumsum
  ) %>%
  as.data.frame()

```





```{r poisson}
library(fitdistrplus)

hpk_hist %>% dplyr::filter(stat_name == 'R') %>%
  dplyr::select(value) %>% ggplot(aes(x = value)) + geom_histogram()

& team_key == '328.l.69518.t.11'
stat_data <- hpk_hist %>% dplyr::filter(stat_name == 'TB' ) %>% dplyr::select(value) %>% unlist() %>% unname()
  
stat_fit <- fitdist(
  data = stat_data,
  distr = 'nbinom',
  method = "mle"
)
summary(stat_fit)
plot(stat_fit)

sim <- rnbinom(
  n = length(stat_data), 
  size = stat_fit$estimate[1],
  mu = stat_fit$estimate[2]
)

check_fit <- data.frame(
  stat = c(stat_data, sim),
  origin = c(rep('observed', length(stat_data)), rep('simulated', length(sim))),
  stringsAsFactors = FALSE
)

ggplot(
  data = check_fit,
  aes(
    x = stat,
    group = origin,
    color = origin
  )
) +
geom_density(
  adjust = 2
) +
theme_bw()

```


reasonable start values
```{r}

for (i in c('R', 'RBI', 'SB', 'TB', 'OB', 'PA', 'W', 
                  'SV', 'K', 'Runs Allowed', 'WH Allowed', 'H', 'AB')) {
  
  print(i)
  stat_data <- hpk_hist %>% dplyr::filter(stat_name == i) %>% 
    dplyr::select(value) %>% unlist() %>% unname()
  
  stat_fit <- fitdist(
    data = stat_data,
    distr = 'nbinom',
    method = "mle"
  )
  print(summary(stat_fit))

}
```


# testing 

```{r try_it, eval = FALSE}

h_table_rank(hpk_week) %>% as.data.frame()
h_table_rank(hpk_month) %>% as.data.frame()

h_table_stats(hpk_week) %>% as.data.frame()
h_table_stats(hpk_month) %>% as.data.frame()

p_table_rank(hpk_week) %>% as.data.frame()
p_table_rank(hpk_month) %>% as.data.frame()

p_table_stats(hpk_week) %>% as.data.frame()
p_table_stats(hpk_month) %>% as.data.frame()

all_table_stats(hpk_month) %>% as.data.frame()
all_table_rank(hpk_month) %>% as.data.frame()

```
